# cf.: https://raw.githubusercontent.com/levlaz/circleci.py/master/.circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout

      - restore_cache:
          key: v1-dependency-cache-{{ checksum "requirements.txt" }}

      - run:
          name: install python dependencies
          command: |
            pip install --upgrade pip
            pip install poetry
            poetry export --dev --format "requirements.txt" --without-hashes --output requirements.txt
            pip install -r requirements.txt

      - save_cache:
          key: v1-dependency-cache-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

  deploy:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout

      - restore_cache:
          key: v1-dependency-cache-{{ checksum "requirements.txt" }}

      - run:
          name: install python dependencies
          command: |
            pip install --upgrade pip
            pip install poetry
            poetry export --dev --format "requirements.txt" --without-hashes --output requirements.txt
            pip install -r requirements.txt

      - save_cache:
          key: v1-dependency-cache-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            . venv/bin/activate
            python3 setup.py install
            python3 setup.py sdist
            python3 setup.py bdist_wheel

      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(\.[0-9]+)*/
            branches:
              ignore: /.*/
